const recommendedDataDetailed = {
   "ChIJ9590IY3AwoARquS6ie60MUc":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJywjU6WG_woAR3NrWwrEH_3M":{
      "permanently_closed":true
   },
   "ChIJzYw8m0XGwoARtW9e8GrL0ec":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJF5HzXyO_woARWLb_VYuPf6M":{
      "permanently_closed":true
   },
   "ChIJBTk8wjy5woARmunGKGJ3PCI":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJS8kiFbPHwoAR2U3en8iDAzI":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJf6rEBkzGwoARAxCe3iG0wk0":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJJahUMKDHwoARRHeOMRK0ssw":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJ_yD1_SK5woARmWLyCit3znQ":{
      "permanently_closed":true
   },
   "ChIJE3oivcfHwoARF5aopvG60T4":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJdZbSPDg23YAR6yR-akC2g4E":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJiY0oaS7HwoAR5LI-3GTICJY":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJ8eE_O7PHwoAR9GIOBGi7Nhc":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJ1bvx4cfHwoARBiDLwxn734c":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJm6deTdekwoARTY_RzhoRms0":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJY79CabLHwoARCEywRMdQnZE":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJe7jY6rm6woARcQrmHxB-EGM":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJweei5UvGwoARCyOImMhwE70":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJuY2Kw7LHwoARE67ZSBgACSw":{
      "opening_hours":{
         "open_now":true
      }
   },
   "ChIJ7R_mFrfHwoARHQlClfDAjUg":{
      "opening_hours":{
         "open_now":true
      }
   }
};

export default recommendedDataDetailed;
